name: git_conflict

on:
  push:
    branches: [ "main" ]
    tags: "release-*"
  pull_request:
    branches: [ "main" ]
    tags: "release-*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --workspace --verbose
    - name: test
      run: cargo test --workspace --all-features 
    - name: Build and deploy 
      run : cargo publish --workspace --no-verify --token ${{ secrets.CARGO_KEY }}
